# Site settings
title: Mission Digest | a free monthly newsletter for Austin changemakers
email: missiondigest@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A monthly email series highlighting the people who make a difference in their communities each and every day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.missiondigest.com" # the base hostname & protocol for your site
twitter_username: missiondigest
instagram_username:  missiondigest

# Build settings
markdown: kramdown
